import type { Gradient, Category } from "../types"
import type { NamedPreset } from "../factories"
import { FACTORY_MAP } from "../factories"

function g(category: Category, seeds: NamedPreset[]): Gradient[] {
  return seeds.map((seed) => FACTORY_MAP[category](seed))
}

const auroraSeeds: NamedPreset[] = [
  { id: "aurora-borealis-veil", name: "Borealis Veil", desc: "Classic green-cyan curtains", mood: "cool", colors: ["#4ade80", "#22d3ee", "#818cf8", "#34d399"], dark: true },
  { id: "aurora-blood-curtain", name: "Blood Curtain", desc: "Rare red aurora sheets", mood: "warm", colors: ["#fb7185", "#ef4444", "#fb923c", "#9f1239"], dark: true },
  { id: "aurora-violet-arc", name: "Violet Arc", desc: "Violet arc over a dark ridge", mood: "vivid", colors: ["#a78bfa", "#e879f9", "#6366f1", "#22d3ee"], dark: true },
  { id: "aurora-mint-drape", name: "Mint Drape", desc: "Mint drapes in polar night", mood: "cool", colors: ["#5eead4", "#34d399", "#67e8f9", "#14b8a6"], dark: true },
  { id: "aurora-gold-veil", name: "Gold Veil", desc: "Gold-tinted polar veil", mood: "warm", colors: ["#fbbf24", "#f59e0b", "#84cc16", "#fde68a"], dark: true },
  { id: "aurora-ice-ribbon", name: "Ice Ribbon", desc: "Ice-blue ribbons in the sky", mood: "cool", colors: ["#7dd3fc", "#38bdf8", "#a5b4fc", "#22d3ee"], dark: true },
  { id: "aurora-magenta-fold", name: "Magenta Fold", desc: "Magenta folds in polar dark", mood: "vivid", colors: ["#f472b6", "#c084fc", "#22d3ee", "#e879f9"], dark: true },
  { id: "aurora-jade-sheet", name: "Jade Sheet", desc: "Jade sheets over tundra", mood: "cool", colors: ["#4ade80", "#14b8a6", "#22d3ee", "#86efac"], dark: true },
  { id: "aurora-copper-arc", name: "Copper Arc", desc: "Copper arc at the horizon", mood: "warm", colors: ["#fb923c", "#f59e0b", "#ef4444", "#fdba74"], dark: true },
  { id: "aurora-indigo-drape", name: "Indigo Drape", desc: "Indigo drapes with cyan edge", mood: "dark", colors: ["#6366f1", "#4f46e5", "#22d3ee", "#818cf8"], dark: true },
  { id: "aurora-chartreuse", name: "Chartreuse Curtain", desc: "Chartreuse polar curtain", mood: "vivid", colors: ["#a3e635", "#22d3ee", "#84cc16", "#67e8f9"], dark: true },
  { id: "aurora-rose-arc", name: "Rose Arc", desc: "Rose arc in polar twilight", mood: "warm", colors: ["#fb7185", "#f9a8d4", "#c084fc", "#fda4af"], dark: true },
  { id: "aurora-steel-veil", name: "Steel Veil", desc: "Steel-grey polar veil", mood: "cool", colors: ["#94a3b8", "#38bdf8", "#64748b", "#7dd3fc"], dark: true },
  { id: "aurora-emerald-fold", name: "Emerald Fold", desc: "Emerald folds, slow motion", mood: "cool", colors: ["#34d399", "#10b981", "#22d3ee", "#6ee7b7"], dark: true },
  { id: "aurora-orchid-sheet", name: "Orchid Sheet", desc: "Orchid sheets over snow", mood: "vivid", colors: ["#e879f9", "#a78bfa", "#22d3ee", "#f0abfc"], dark: true },
  { id: "aurora-amber-drape", name: "Amber Drape", desc: "Amber drapes at polar dusk", mood: "warm", colors: ["#fbbf24", "#f97316", "#84cc16", "#fde68a"], dark: true },
  { id: "aurora-cyan-ribbon", name: "Cyan Ribbon", desc: "Thin cyan ribbons, high sky", mood: "cool", colors: ["#22d3ee", "#67e8f9", "#818cf8", "#06b6d4"], dark: true },
  { id: "aurora-wine-curtain", name: "Wine Curtain", desc: "Wine-dark polar curtain", mood: "dark", colors: ["#9f1239", "#fb7185", "#7c3aed", "#be123c"], dark: true },
  { id: "aurora-peridot-arc", name: "Peridot Arc", desc: "Peridot arc with teal edge", mood: "cool", colors: ["#a3e635", "#2dd4bf", "#22d3ee", "#4ade80"], dark: true },
  { id: "aurora-lilac-veil", name: "Lilac Veil", desc: "Lilac veil over polar ice", mood: "cool", colors: ["#c4b5fd", "#a78bfa", "#67e8f9", "#ddd6fe"], dark: true },
  { id: "aurora-ember-fold", name: "Ember Fold", desc: "Ember folds at the horizon", mood: "warm", colors: ["#ef4444", "#fb923c", "#fbbf24", "#f97316"], dark: true },
  { id: "aurora-aqua-sheet", name: "Aqua Sheet", desc: "Aqua sheets, almost liquid", mood: "cool", colors: ["#67e8f9", "#2dd4bf", "#38bdf8", "#22d3ee"], dark: true },
  { id: "aurora-fuchsia-drape", name: "Fuchsia Drape", desc: "Fuchsia drapes in void", mood: "vivid", colors: ["#e879f9", "#db2777", "#818cf8", "#f472b6"], dark: true },
  { id: "aurora-olive-arc", name: "Olive Arc", desc: "Olive arc, muted polar light", mood: "warm", colors: ["#84cc16", "#ca8a04", "#22d3ee", "#a3e635"], dark: true },
  { id: "aurora-sapphire", name: "Sapphire Curtain", desc: "Sapphire curtains, deep night", mood: "cool", colors: ["#3b82f6", "#22d3ee", "#6366f1", "#60a5fa"], dark: true },
  { id: "aurora-peach-veil", name: "Peach Veil", desc: "Peach veil in polar twilight", mood: "warm", colors: ["#fdba74", "#fb7185", "#fbbf24", "#fed7aa"], dark: true },
  { id: "aurora-teal-ribbon", name: "Teal Ribbon", desc: "Teal ribbons over tundra", mood: "cool", colors: ["#14b8a6", "#22d3ee", "#34d399", "#5eead4"], dark: true },
  { id: "aurora-plum-fold", name: "Plum Fold", desc: "Plum folds with cyan sparks", mood: "dark", colors: ["#6b21a8", "#c084fc", "#22d3ee", "#7e22ce"], dark: true },
  { id: "aurora-lime-sheet", name: "Lime Sheet", desc: "Lime sheets, electric polar", mood: "vivid", colors: ["#a3e635", "#22d3ee", "#84cc16", "#bef264"], dark: true },
  { id: "aurora-bronze-drape", name: "Bronze Drape", desc: "Bronze drapes at polar dusk", mood: "warm", colors: ["#d97706", "#ea580c", "#84cc16", "#fbbf24"], dark: true },
  { id: "aurora-icegreen", name: "Icegreen Arc", desc: "Ice-green arc, almost white", mood: "cool", colors: ["#ccfbf1", "#5eead4", "#67e8f9", "#a7f3d0"], dark: true },
  { id: "aurora-hot-pink", name: "Hot Pink Curtain", desc: "Hot pink polar curtain", mood: "vivid", colors: ["#f472b6", "#22d3ee", "#c084fc", "#fb7185"], dark: true },
  { id: "aurora-slate-veil", name: "Slate Veil", desc: "Slate veil with a cyan edge", mood: "dark", colors: ["#475569", "#38bdf8", "#64748b", "#22d3ee"], dark: true },
  { id: "aurora-honey-arc", name: "Honey Arc", desc: "Honey arc over dark pines", mood: "warm", colors: ["#fbbf24", "#84cc16", "#f59e0b", "#fde68a"], dark: true },
]

const noiseSeeds: NamedPreset[] = [
  { id: "noise-sepia-wash", name: "Sepia Wash", desc: "Sepia wash with analog grit", mood: "warm", colors: ["#f5e6c8", "#d4a373", "#9a3412"], grain: true },
  { id: "noise-cyan-static", name: "Cyan Static", desc: "Cyan static on a cool field", mood: "cool", colors: ["#0ea5e9", "#1d4ed8", "#67e8f9"], dark: true, grain: true },
  { id: "noise-rose-hiss", name: "Rose Hiss", desc: "Rose field, tape hiss", mood: "warm", colors: ["#fecdd3", "#fb7185", "#9f1239"], grain: true },
  { id: "noise-olive-grit", name: "Olive Grit", desc: "Olive wall with grit", mood: "warm", colors: ["#ecfccb", "#84cc16", "#3f6212"], grain: true },
  { id: "noise-night-snow", name: "Night Snow", desc: "Night snow, heavy grain", mood: "dark", colors: ["#0f172a", "#1e293b", "#38bdf8"], dark: true, grain: true },
  { id: "noise-peach-hiss", name: "Peach Hiss", desc: "Peach daylight with hiss", mood: "warm", colors: ["#ffedd5", "#fdba74", "#ea580c"], grain: true },
  { id: "noise-violet-static", name: "Violet Static", desc: "Violet static, CRT snow", mood: "vivid", colors: ["#2e1065", "#7c3aed", "#e879f9"], dark: true, grain: true },
  { id: "noise-fog-hiss", name: "Fog Hiss", desc: "Fogged grey with grain", mood: "cool", colors: ["#e2e8f0", "#94a3b8", "#64748b"], grain: true },
  { id: "noise-ember-grit", name: "Ember Grit", desc: "Ember wall, heavy grit", mood: "warm", colors: ["#431407", "#c2410c", "#fb923c"], dark: true, grain: true },
  { id: "noise-mint-static", name: "Mint Static", desc: "Mint field with analog static", mood: "cool", colors: ["#ccfbf1", "#14b8a6", "#134e4a"], grain: true },
  { id: "noise-wine-hiss", name: "Wine Hiss", desc: "Wine-dark field, tape hiss", mood: "dark", colors: ["#4c0519", "#9f1239", "#fb7185"], dark: true, grain: true },
  { id: "noise-sand-grit", name: "Sand Grit", desc: "Sand field, overexposed grit", mood: "warm", colors: ["#fef3c7", "#f59e0b", "#92400e"], grain: true },
  { id: "noise-cobalt-static", name: "Cobalt Static", desc: "Cobalt static, late-night TV", mood: "cool", colors: ["#1e3a8a", "#2563eb", "#7dd3fc"], dark: true, grain: true },
  { id: "noise-chartreuse", name: "Chartreuse Noise", desc: "Chartreuse field, loud grain", mood: "vivid", colors: ["#ecfccb", "#a3e635", "#365314"], grain: true },
  { id: "noise-blush-hiss", name: "Blush Hiss", desc: "Blush paper with hiss", mood: "warm", colors: ["#ffe4e6", "#fda4af", "#fb7185"], grain: true },
  { id: "noise-slate-snow", name: "Slate Snow", desc: "Slate field, fine snow", mood: "cool", colors: ["#334155", "#64748b", "#38bdf8"], dark: true, grain: true },
  { id: "noise-gold-grit", name: "Gold Grit", desc: "Gold wash with grit", mood: "warm", colors: ["#fde68a", "#d97706", "#78350f"], grain: true },
  { id: "noise-teal-static", name: "Teal Static", desc: "Teal static on dark glass", mood: "cool", colors: ["#134e4a", "#14b8a6", "#67e8f9"], dark: true, grain: true },
  { id: "noise-magenta-hiss", name: "Magenta Hiss", desc: "Magenta hiss, analog bloom", mood: "vivid", colors: ["#701a75", "#d946ef", "#c084fc"], dark: true, grain: true },
  { id: "noise-umber-grit", name: "Umber Grit", desc: "Umber wall, dusty grit", mood: "warm", colors: ["#f5e6c8", "#a16207", "#7c2d12"], grain: true },
  { id: "noise-ice-static", name: "Ice Static", desc: "Ice field with pale static", mood: "cool", colors: ["#e0f2fe", "#38bdf8", "#64748b"], grain: true },
  { id: "noise-ruby-hiss", name: "Ruby Hiss", desc: "Ruby field, heavy hiss", mood: "vivid", colors: ["#4c0519", "#e11d48", "#fb7185"], dark: true, grain: true },
  { id: "noise-chrome-snow", name: "Chrome Snow", desc: "Chrome field, fine snow", mood: "cool", colors: ["#f8fafc", "#94a3b8", "#0ea5e9"], grain: true },
  { id: "noise-saffron-grit", name: "Saffron Grit", desc: "Saffron wash, dusty grit", mood: "warm", colors: ["#fef9c3", "#eab308", "#b45309"], grain: true },
  { id: "noise-jade-static", name: "Jade Static", desc: "Jade static, analog green", mood: "cool", colors: ["#064e3b", "#10b981", "#67e8f9"], dark: true, grain: true },
  { id: "noise-plum-hiss", name: "Plum Hiss", desc: "Plum field with tape hiss", mood: "dark", colors: ["#3b0764", "#7e22ce", "#e879f9"], dark: true, grain: true },
  { id: "noise-lime-grit", name: "Lime Grit", desc: "Lime field, graphic grit", mood: "vivid", colors: ["#ecfccb", "#84cc16", "#3f6212"], grain: true },
  { id: "noise-bronze-hiss", name: "Bronze Hiss", desc: "Bronze wash, analog hiss", mood: "warm", colors: ["#451a03", "#b45309", "#fbbf24"], dark: true, grain: true },
  { id: "noise-sky-static", name: "Sky Static", desc: "Sky-blue static, daylight TV", mood: "cool", colors: ["#e0f2fe", "#0ea5e9", "#1d4ed8"], grain: true },
  { id: "noise-berry-grit", name: "Berry Grit", desc: "Berry wash with grit", mood: "vivid", colors: ["#fce7f3", "#db2777", "#9d174d"], grain: true },
  { id: "noise-paper-hiss", name: "Paper Hiss", desc: "Warm paper, almost empty grain", mood: "warm", colors: ["#f8f6f0", "#e7e5e4", "#a8a29e"], grain: true },
  { id: "noise-ink-snow", name: "Ink Snow", desc: "Ink field with white snow", mood: "dark", colors: ["#0d0b09", "#1c1917", "#a8a29e"], dark: true, grain: true },
]

const haloSeeds: NamedPreset[] = [
  { id: "halo-solar-core", name: "Solar Core", desc: "A bright solar halo in void", mood: "warm", colors: ["#fde68a", "#f59e0b", "#ea580c"], dark: true },
  { id: "halo-ice-ring", name: "Ice Ring", desc: "Pale ice ring, polar sun", mood: "cool", colors: ["#e0f2fe", "#38bdf8", "#818cf8"], dark: true },
  { id: "halo-neon-orbit", name: "Neon Orbit", desc: "Neon orbital ring", mood: "vivid", colors: ["#22d3ee", "#a3e635", "#f472b6"], dark: true },
  { id: "halo-rose-corona", name: "Rose Corona", desc: "Rose corona around a dark core", mood: "warm", colors: ["#fecdd3", "#fb7185", "#9f1239"], dark: true },
  { id: "halo-violet-ring", name: "Violet Ring", desc: "Violet ring in deep space", mood: "cool", colors: ["#c4b5fd", "#7c3aed", "#22d3ee"], dark: true },
  { id: "halo-gold-orbit", name: "Gold Orbit", desc: "Gold orbit around a dark star", mood: "warm", colors: ["#fde68a", "#d97706", "#92400e"], dark: true },
  { id: "halo-mint-corona", name: "Mint Corona", desc: "Mint corona, clinic dark", mood: "cool", colors: ["#ccfbf1", "#14b8a6", "#134e4a"], dark: true },
  { id: "halo-ember-ring", name: "Ember Ring", desc: "Ember ring, forge light", mood: "warm", colors: ["#fb923c", "#ef4444", "#7c2d12"], dark: true },
  { id: "halo-cyan-orbit", name: "Cyan Orbit", desc: "Cyan orbit, machine glow", mood: "cool", colors: ["#a5f3fc", "#22d3ee", "#155e75"], dark: true },
  { id: "halo-magenta-core", name: "Magenta Core", desc: "Magenta core with a tight ring", mood: "vivid", colors: ["#f0abfc", "#d946ef", "#6b21a8"], dark: true },
  { id: "halo-steel-ring", name: "Steel Ring", desc: "Steel ring, industrial halo", mood: "cool", colors: ["#e2e8f0", "#64748b", "#0ea5e9"], dark: true },
  { id: "halo-chartreuse", name: "Chartreuse Halo", desc: "Chartreuse halo, toxic glow", mood: "vivid", colors: ["#ecfccb", "#a3e635", "#365314"], dark: true },
  { id: "halo-wine-corona", name: "Wine Corona", desc: "Wine corona in a dark room", mood: "dark", colors: ["#fecdd3", "#9f1239", "#4c0519"], dark: true },
  { id: "halo-fog-ring", name: "Fog Ring", desc: "Fog ring, almost gone", mood: "cool", colors: ["#f8fafc", "#94a3b8", "#334155"], dark: true },
  { id: "halo-peach-orbit", name: "Peach Orbit", desc: "Peach orbit at dusk", mood: "warm", colors: ["#ffedd5", "#fdba74", "#ea580c"], dark: true },
  { id: "halo-indigo-core", name: "Indigo Core", desc: "Indigo core with a cyan ring", mood: "dark", colors: ["#c7d2fe", "#4338ca", "#22d3ee"], dark: true },
  { id: "halo-lime-ring", name: "Lime Ring", desc: "Lime ring, graphic glow", mood: "vivid", colors: ["#ecfccb", "#84cc16", "#365314"], dark: true },
  { id: "halo-blush-corona", name: "Blush Corona", desc: "Blush corona, studio dark", mood: "warm", colors: ["#ffe4e6", "#fb7185", "#9f1239"], dark: true },
  { id: "halo-slate-orbit", name: "Slate Orbit", desc: "Slate orbit with a blue edge", mood: "cool", colors: ["#f1f5f9", "#475569", "#38bdf8"], dark: true },
  { id: "halo-amber-core", name: "Amber Core", desc: "Amber core, lantern halo", mood: "warm", colors: ["#fde68a", "#f59e0b", "#78350f"], dark: true },
  { id: "halo-teal-ring", name: "Teal Ring", desc: "Teal ring in a black tank", mood: "cool", colors: ["#ccfbf1", "#0d9488", "#134e4a"], dark: true },
  { id: "halo-orchid-orbit", name: "Orchid Orbit", desc: "Orchid orbit, night club", mood: "vivid", colors: ["#fae8ff", "#e879f9", "#6b21a8"], dark: true },
  { id: "halo-umber-corona", name: "Umber Corona", desc: "Umber corona, earth lamp", mood: "warm", colors: ["#f5e6c8", "#a16207", "#431407"], dark: true },
  { id: "halo-icegreen", name: "Icegreen Halo", desc: "Ice-green halo, polar lamp", mood: "cool", colors: ["#ecfdf5", "#14b8a6", "#022c22"], dark: true },
  { id: "halo-ruby-ring", name: "Ruby Ring", desc: "Ruby ring, jewelry light", mood: "vivid", colors: ["#ffe4e6", "#e11d48", "#4c0519"], dark: true },
  { id: "halo-chrome-core", name: "Chrome Core", desc: "Chrome core with a cool ring", mood: "cool", colors: ["#f8fafc", "#94a3b8", "#0f172a"], dark: true },
  { id: "halo-saffron-orbit", name: "Saffron Orbit", desc: "Saffron orbit, temple lamp", mood: "warm", colors: ["#fef9c3", "#eab308", "#78350f"], dark: true },
  { id: "halo-jade-corona", name: "Jade Corona", desc: "Jade corona in a dark room", mood: "cool", colors: ["#d1fae5", "#059669", "#022c22"], dark: true },
  { id: "halo-plum-ring", name: "Plum Ring", desc: "Plum ring, velvet dark", mood: "dark", colors: ["#f3e8ff", "#6b21a8", "#3b0764"], dark: true },
  { id: "halo-bronze-core", name: "Bronze Core", desc: "Bronze core, foundry halo", mood: "warm", colors: ["#fef3c7", "#b45309", "#451a03"], dark: true },
  { id: "halo-sky-orbit", name: "Sky Orbit", desc: "Sky-blue orbit on night ink", mood: "cool", colors: ["#e0f2fe", "#0ea5e9", "#0c4a6e"], dark: true },
  { id: "halo-berry-corona", name: "Berry Corona", desc: "Berry corona, night fruit", mood: "vivid", colors: ["#fce7f3", "#db2777", "#831843"], dark: true },
  { id: "halo-paper-ring", name: "Paper Ring", desc: "Paper-white ring on charcoal", mood: "cool", colors: ["#fafaf9", "#a8a29e", "#1c1917"], dark: true },
  { id: "halo-plasma-core", name: "Plasma Core", desc: "Plasma core, fusion glow", mood: "vivid", colors: ["#22d3ee", "#818cf8", "#f472b6"], dark: true },
]

const duskSeeds: NamedPreset[] = [
  { id: "dusk-ember-line", name: "Ember Line", desc: "Ember horizon over cool night", mood: "warm", colors: ["#1e1b4b", "#fb923c", "#7c2d12"], dark: true },
  { id: "dusk-lilac-band", name: "Lilac Band", desc: "Lilac band between day and night", mood: "cool", colors: ["#312e81", "#c4b5fd", "#1e1b4b"], dark: true },
  { id: "dusk-gold-cut", name: "Gold Cut", desc: "A gold cut across the horizon", mood: "warm", colors: ["#0f172a", "#fbbf24", "#78350f"], dark: true },
  { id: "dusk-mint-line", name: "Mint Line", desc: "Mint afterglow on a cool sky", mood: "cool", colors: ["#0f172a", "#5eead4", "#134e4a"], dark: true },
  { id: "dusk-rose-band", name: "Rose Band", desc: "Rose band, last light", mood: "warm", colors: ["#1c1917", "#fb7185", "#9f1239"], dark: true },
  { id: "dusk-cyan-cut", name: "Cyan Cut", desc: "Cyan cut under a navy sky", mood: "cool", colors: ["#0b1220", "#22d3ee", "#0c4a6e"], dark: true },
  { id: "dusk-violet-line", name: "Violet Line", desc: "Violet line, civil twilight", mood: "vivid", colors: ["#1e1b4b", "#a78bfa", "#4c1d95"], dark: true },
  { id: "dusk-olive-band", name: "Olive Band", desc: "Olive band over dark hills", mood: "warm", colors: ["#1c1917", "#84cc16", "#365314"], dark: true },
  { id: "dusk-peach-cut", name: "Peach Cut", desc: "Peach cut, suburban dusk", mood: "warm", colors: ["#1e1b4b", "#fdba74", "#9a3412"], dark: true },
  { id: "dusk-steel-line", name: "Steel Line", desc: "Steel line, industrial dusk", mood: "cool", colors: ["#0f172a", "#94a3b8", "#334155"], dark: true },
  { id: "dusk-berry-band", name: "Berry Band", desc: "Berry band, late summer dusk", mood: "vivid", colors: ["#1c1917", "#db2777", "#831843"], dark: true },
  { id: "dusk-amber-cut", name: "Amber Cut", desc: "Amber cut across farmland", mood: "warm", colors: ["#1c1917", "#f59e0b", "#78350f"], dark: true },
  { id: "dusk-cobalt-line", name: "Cobalt Line", desc: "Cobalt line, maritime dusk", mood: "cool", colors: ["#0b1220", "#3b82f6", "#1e3a8a"], dark: true },
  { id: "dusk-chartreuse", name: "Chartreuse Band", desc: "Chartreuse band, weird dusk", mood: "vivid", colors: ["#0f172a", "#a3e635", "#365314"], dark: true },
  { id: "dusk-wine-cut", name: "Wine Cut", desc: "Wine cut, vineyard dusk", mood: "dark", colors: ["#1c1917", "#9f1239", "#4c0519"], dark: true },
  { id: "dusk-fog-line", name: "Fog Line", desc: "Fog line, almost no color", mood: "cool", colors: ["#1e293b", "#94a3b8", "#0f172a"], dark: true },
  { id: "dusk-saffron-band", name: "Saffron Band", desc: "Saffron band over desert", mood: "warm", colors: ["#1c1917", "#eab308", "#78350f"], dark: true },
  { id: "dusk-teal-cut", name: "Teal Cut", desc: "Teal cut, coastal dusk", mood: "cool", colors: ["#042f2e", "#14b8a6", "#134e4a"], dark: true },
  { id: "dusk-magenta-line", name: "Magenta Line", desc: "Magenta line, city dusk", mood: "vivid", colors: ["#1e1b4b", "#d946ef", "#701a75"], dark: true },
  { id: "dusk-umber-band", name: "Umber Band", desc: "Umber band, earth dusk", mood: "warm", colors: ["#1c1917", "#a16207", "#431407"], dark: true },
  { id: "dusk-ice-cut", name: "Ice Cut", desc: "Ice cut, polar dusk", mood: "cool", colors: ["#0b1220", "#7dd3fc", "#0c4a6e"], dark: true },
  { id: "dusk-ruby-line", name: "Ruby Line", desc: "Ruby line, alpine dusk", mood: "vivid", colors: ["#1c1917", "#e11d48", "#4c0519"], dark: true },
  { id: "dusk-chrome-band", name: "Chrome Band", desc: "Chrome band, urban dusk", mood: "cool", colors: ["#0f172a", "#cbd5e1", "#334155"], dark: true },
  { id: "dusk-honey-cut", name: "Honey Cut", desc: "Honey cut over dark pines", mood: "warm", colors: ["#1c1917", "#fbbf24", "#78350f"], dark: true },
  { id: "dusk-jade-line", name: "Jade Line", desc: "Jade line, forest dusk", mood: "cool", colors: ["#022c22", "#10b981", "#064e3b"], dark: true },
  { id: "dusk-plum-band", name: "Plum Band", desc: "Plum band, orchard dusk", mood: "dark", colors: ["#1e1b4b", "#6b21a8", "#3b0764"], dark: true },
  { id: "dusk-lime-cut", name: "Lime Cut", desc: "Lime cut, electric dusk", mood: "vivid", colors: ["#0f172a", "#84cc16", "#365314"], dark: true },
  { id: "dusk-bronze-line", name: "Bronze Line", desc: "Bronze line, foundry dusk", mood: "warm", colors: ["#1c1917", "#b45309", "#451a03"], dark: true },
  { id: "dusk-sky-band", name: "Sky Band", desc: "Sky band, last blue hour", mood: "cool", colors: ["#0b1220", "#0ea5e9", "#0c4a6e"], dark: true },
  { id: "dusk-berry-cut", name: "Berry Cut", desc: "Berry cut, orchard night", mood: "vivid", colors: ["#1c1917", "#db2777", "#831843"], dark: true },
  { id: "dusk-paper-line", name: "Paper Line", desc: "Paper-white line on charcoal", mood: "cool", colors: ["#1c1917", "#e7e5e4", "#0c0a09"], dark: true },
  { id: "dusk-plasma-band", name: "Plasma Band", desc: "Plasma band, sci-fi dusk", mood: "vivid", colors: ["#0b1220", "#22d3ee", "#6b21a8"], dark: true },
  { id: "dusk-sand-cut", name: "Sand Cut", desc: "Sand cut, desert blue hour", mood: "warm", colors: ["#1c1917", "#d4a373", "#78350f"], dark: true },
  { id: "dusk-indigo-line", name: "Indigo Line", desc: "Indigo line, nautical dusk", mood: "dark", colors: ["#020617", "#4338ca", "#1e1b4b"], dark: true },
]

export const NEW_CATEGORY_PRESETS: Gradient[] = [
  ...g("aurora", auroraSeeds),
  ...g("noise", noiseSeeds),
  ...g("halo", haloSeeds),
  ...g("dusk", duskSeeds),
]
